//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financial.Internationalization.Entities.Purchase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PurchaseEntityLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseEntityLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financial.Internationalization.Entities.Purchase.PurchaseEntityLabels", typeof(PurchaseEntityLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card used.
        /// </summary>
        internal static string Field_CreditCard {
            get {
                return ResourceManager.GetString("Field_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Field_Description {
            get {
                return ResourceManager.GetString("Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description of the purchase.
        /// </summary>
        internal static string Field_Description_Placeholder {
            get {
                return ResourceManager.GetString("Field_Description_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalment Split.
        /// </summary>
        internal static string Field_InstalmentSplit {
            get {
                return ResourceManager.GetString("Field_InstalmentSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of instalments.
        /// </summary>
        internal static string Field_InstalmentSplit_Placeholder {
            get {
                return ResourceManager.GetString("Field_InstalmentSplit_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Purchase.
        /// </summary>
        internal static string Field_PurchasedOn {
            get {
                return ResourceManager.GetString("Field_PurchasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string Field_TotalAmount {
            get {
                return ResourceManager.GetString("Field_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount of this purchase.
        /// </summary>
        internal static string Field_TotalAmount_Placeholder {
            get {
                return ResourceManager.GetString("Field_TotalAmount_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Delete the &apos;%p&apos; purchase?.
        /// </summary>
        internal static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase &apos;%p&apos; was deleted..
        /// </summary>
        internal static string Message_Deleted {
            get {
                return ResourceManager.GetString("Message_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase &apos;%p&apos; was updated..
        /// </summary>
        internal static string Message_Modified {
            get {
                return ResourceManager.GetString("Message_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase &apos;%p&apos; was added..
        /// </summary>
        internal static string Message_New {
            get {
                return ResourceManager.GetString("Message_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no registered Purchase yet..
        /// </summary>
        internal static string Message_NoRegisteredYet {
            get {
                return ResourceManager.GetString("Message_NoRegisteredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase with id &apos;%i&apos; don&apos;t exists..
        /// </summary>
        internal static string Message_NotFoundById {
            get {
                return ResourceManager.GetString("Message_NotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string This {
            get {
                return ResourceManager.GetString("This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Purchase.
        /// </summary>
        internal static string This_Delete_Title {
            get {
                return ResourceManager.GetString("This_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify this Purchase.
        /// </summary>
        internal static string This_Edit_Title {
            get {
                return ResourceManager.GetString("This_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of your Purchases.
        /// </summary>
        internal static string This_List_Title {
            get {
                return ResourceManager.GetString("This_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new Purchase.
        /// </summary>
        internal static string This_New_Title {
            get {
                return ResourceManager.GetString("This_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        internal static string This_Plural {
            get {
                return ResourceManager.GetString("This_Plural", resourceCulture);
            }
        }
    }
}
