//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financial.Internationalization.Entities.Subscription {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubscriptionEntityLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubscriptionEntityLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financial.Internationalization.Entities.Subscription.SubscriptionEntityLabels", typeof(SubscriptionEntityLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Date.
        /// </summary>
        public static string Field_CancellationDate {
            get {
                return ResourceManager.GetString("Field_CancellationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card used.
        /// </summary>
        public static string Field_CreditCard {
            get {
                return ResourceManager.GetString("Field_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Field_Description {
            get {
                return ResourceManager.GetString("Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description of the service.
        /// </summary>
        public static string Field_Description_Placeholder {
            get {
                return ResourceManager.GetString("Field_Description_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Field_Price {
            get {
                return ResourceManager.GetString("Field_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Price.
        /// </summary>
        public static string Field_Price_Placeholder {
            get {
                return ResourceManager.GetString("Field_Price_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Date.
        /// </summary>
        public static string Field_SignatureDate {
            get {
                return ResourceManager.GetString("Field_SignatureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Delete the &apos;%s&apos; subscription?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription &apos;%p&apos; was deleted..
        /// </summary>
        public static string Message_Deleted {
            get {
                return ResourceManager.GetString("Message_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription &apos;%p&apos; was updated..
        /// </summary>
        public static string Message_Modified {
            get {
                return ResourceManager.GetString("Message_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription &apos;%p&apos; was added..
        /// </summary>
        public static string Message_New {
            get {
                return ResourceManager.GetString("Message_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no registered Subscription yet..
        /// </summary>
        public static string Message_NoRegisteredYet {
            get {
                return ResourceManager.GetString("Message_NoRegisteredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription with id &apos;%i&apos; don&apos;t exists..
        /// </summary>
        public static string Message_NotFoundById {
            get {
                return ResourceManager.GetString("Message_NotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string This {
            get {
                return ResourceManager.GetString("This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Subscription.
        /// </summary>
        public static string This_Delete_Title {
            get {
                return ResourceManager.GetString("This_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify this Subscription.
        /// </summary>
        public static string This_Edit_Title {
            get {
                return ResourceManager.GetString("This_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of your Subscriptions.
        /// </summary>
        public static string This_List_Title {
            get {
                return ResourceManager.GetString("This_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new Subscription.
        /// </summary>
        public static string This_New_Title {
            get {
                return ResourceManager.GetString("This_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string This_Plural {
            get {
                return ResourceManager.GetString("This_Plural", resourceCulture);
            }
        }
    }
}
