//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financial.Internationalization.Entities.CreditCard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreditCardEntityLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreditCardEntityLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financial.Internationalization.Entities.CreditCard.CreditCardEntityLabels", typeof(CreditCardEntityLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        public static string International {
            get {
                return ResourceManager.GetString("International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries to be shown.
        /// </summary>
        public static string Invoice_Empty {
            get {
                return ResourceManager.GetString("Invoice_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string InvoiceDetail_Day {
            get {
                return ResourceManager.GetString("InvoiceDetail_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string InvoiceDetail_Description {
            get {
                return ResourceManager.GetString("InvoiceDetail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string InvoiceDetail_Value {
            get {
                return ResourceManager.GetString("InvoiceDetail_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Delete the &apos;%c&apos; card?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card &apos;%c&apos; was deleted..
        /// </summary>
        public static string Message_Deleted {
            get {
                return ResourceManager.GetString("Message_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card &apos;%c&apos; was updated..
        /// </summary>
        public static string Message_Modified {
            get {
                return ResourceManager.GetString("Message_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card &apos;%c&apos; was added..
        /// </summary>
        public static string Message_New {
            get {
                return ResourceManager.GetString("Message_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card with id &apos;%i&apos; don&apos;t exists..
        /// </summary>
        public static string Message_NotFoundById {
            get {
                return ResourceManager.GetString("Message_NotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname_Placeholder {
            get {
                return ResourceManager.GetString("Nickname_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no registered Credit Card yet.
        /// </summary>
        public static string NoRegisteredYet {
            get {
                return ResourceManager.GetString("NoRegisteredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string This {
            get {
                return ResourceManager.GetString("This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Credit Card.
        /// </summary>
        public static string This_Delete_Title {
            get {
                return ResourceManager.GetString("This_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify this Credit Card .
        /// </summary>
        public static string This_Edit_Title {
            get {
                return ResourceManager.GetString("This_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string This_Invoice {
            get {
                return ResourceManager.GetString("This_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of your Credit Cards.
        /// </summary>
        public static string This_List_Title {
            get {
                return ResourceManager.GetString("This_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new Credit Card .
        /// </summary>
        public static string This_New_Title {
            get {
                return ResourceManager.GetString("This_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cards.
        /// </summary>
        public static string This_Plural {
            get {
                return ResourceManager.GetString("This_Plural", resourceCulture);
            }
        }
    }
}
